import { GoogleGenAI } from "@google/genai";

export const config = {
  api: {
    bodyParser: {
      sizeLimit: '10mb',
    },
  },
};

export default async function handler(req: any, res: any) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: "API Key (GEMINI_API_KEY) is not set on the Vercel server" });
    }

    const { prompt, aspectRatio = "1:1", images = [] } = req.body;
    const ai = new GoogleGenAI({ apiKey });
    
    const parts: any[] = [{ text: prompt }];
    
    for (const img of images) {
      if (img) {
        // Remove data:image/...;base64, prefix if present
        const base64Data = img.split(',')[1] || img;
        parts.push({
          inlineData: {
            mimeType: "image/jpeg",
            data: base64Data,
          },
        });
      }
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: [{ parts }],
      config: {
        imageConfig: {
          aspectRatio,
        },
      },
    });

    let imageData = null;
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        imageData = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        break;
      }
    }

    if (imageData) {
      res.status(200).json({ image: imageData });
    } else {
      res.status(500).json({ error: "No image generated by AI" });
    }

  } catch (error: any) {
    console.error("Vercel Image generation error:", error);
    if (error.message?.includes("429") || error.message?.toLowerCase().includes("quota")) {
      return res.status(429).json({ error: "QUOTA_EXCEEDED" });
    }
    res.status(500).json({ error: error.message || "Internal server error" });
  }
}
